In [1]:
import numpy as np

Creando Arrays

    1 ✅ np.arange (Start,Ens,Steps) → es como el list( range(0,10)) pero como arrange
    2 ✅ np.zeros(n)
    3 ✅ np.ones(n)
    4 ✅ np.linspace(Start, End, Cant n de Start a End)
    5 ✅ np.eye(n) ·· Matriz identidad

Arrays con numeros randoms

    ☑️ np.random.rand(Columnas, Filas, mas dimensiones ) ·· Ambos con numeros randoms
    ☑️ np.random.randint(Start, End, Dimensiones) ·· N random entre Start y End y tupla dims


In [2]:
list (range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(4,2,5)

array([[[0.88565521, 0.81206968, 0.87066889, 0.90225494, 0.30455778],
        [0.38977891, 0.37119845, 0.79446933, 0.56096731, 0.47705761]],

       [[0.28330484, 0.76480322, 0.37505117, 0.268005  , 0.1211112 ],
        [0.25672103, 0.82027633, 0.63104847, 0.53822998, 0.44297336]],

       [[0.69530679, 0.10680675, 0.31286069, 0.86930567, 0.98932854],
        [0.90064829, 0.22569794, 0.98367181, 0.1066278 , 0.0832572 ]],

       [[0.59114066, 0.33520457, 0.86592134, 0.12426591, 0.31440789],
        [0.19142938, 0.42799995, 0.01690979, 0.22437677, 0.24892859]]])

In [20]:
np.random.randint(1,15)

6

In [21]:
np.random.randint(1,100,(10,10))

array([[29, 30, 34, 43, 82, 39, 58, 19, 61, 82],
       [97,  1, 68, 68, 14, 75, 78, 26, 29, 86],
       [75, 31, 66, 72, 12, 91, 54, 55, 63, 40],
       [71,  1, 61, 63, 16, 18, 91, 60,  1, 26],
       [60, 81, 90, 34, 76,  9, 24, 43, 69, 63],
       [32, 60, 48, 19, 49, 26, 86, 20, 91, 74],
       [97, 44, 18, 85, 52, 65, 85, 63, 43, 34],
       [68, 13, 96, 91, 53, 24, 71, 66, 83, 61],
       [91, 39, 45, 21,  2, 97, 43, 38,  9, 44],
       [97, 59, 52, 46, 57, 30, 71, 30, 65, 74]])