In [1]:
import numpy as np

📝Copy

.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
trozo_de_arr = arr[0:6]

In [4]:
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [5]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [6]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [7]:
arr_copy = arr.copy()

In [8]:
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [9]:
arr_copy[:] = 100

In [10]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [11]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])