In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[ 8,  4,  4,  8,  7],
       [ 5, 11,  1,  1, 13]])

In [5]:
arr.max() #return max number from array

13

In [6]:
matriz.max()

13

In [8]:
matriz.max(1)

array([ 8, 13])

In [9]:
matriz.max(0)

array([ 8, 11,  4,  8, 13])

In [ ]:
arr.argmax(0)

9

In [11]:
matriz.argmax(0)

array([0, 1, 0, 0, 1], dtype=int64)

In [12]:
arr.min()

1

In [13]:
matriz.min(0)

array([5, 4, 1, 1, 7])

In [14]:
arr.argmin()

7

In [15]:
matriz.argmin(1)

array([1, 2], dtype=int64)

In [17]:
arr

array([ 8,  4,  4,  8,  7,  5, 11,  1,  1, 13])

In [18]:
arr.ptp() #difference between lowest value respect highest

12

In [19]:
matriz.ptp()

12

In [20]:
matriz.ptp(0)

array([3, 7, 3, 7, 6])

In [22]:
arr

array([ 8,  4,  4,  8,  7,  5, 11,  1,  1, 13])

In [21]:
np.percentile(arr,50)

6.0

In [23]:
arr
arr.sort()
arr

array([ 1,  1,  4,  4,  5,  7,  8,  8, 11, 13])

In [24]:
np.median(arr) # percenti 50 -- half o my array

6.0

In [25]:
np.std(arr)

3.762977544445356

In [26]:
np.var(arr)

14.160000000000002

In [27]:
np.std(arr) **2

14.160000000000002

In [28]:
np.mean(arr) # sum all array values divided by the amount of values in the array

6.2

In [30]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [32]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [33]:
b= np.expand_dims(b,axis=0)

In [34]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
c= np.expand_dims(b,axis=1)

In [36]:
np.concatenate((a,b.T),axis=1) #T == transpuesta de una Matriz

array([[1, 2, 5],
       [3, 4, 6]])