In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2 #mal

[1, 2, 1, 2]

In [6]:
arr = np.arange(0,10)
arr2 = np.copy(arr)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
1/arr

C:\Users\fvaron\AppData\Local\Temp\ipykernel_3004\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
arr  ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
matriz2 = matriz.copy()

In [16]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [17]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [19]:
np.matmul(matriz,matriz2.T) # Producto punto

array([[ 30,  80],
       [ 80, 255]])

In [20]:
matriz @ matriz2.T # Producto punto v2

array([[ 30,  80],
       [ 80, 255]])