In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,2))

In [4]:
arr.shape

(3, 2)

In [5]:
arr

array([[1, 1],
       [5, 9],
       [3, 2]])

In [6]:
arr.reshape(1,6)

array([[1, 1, 5, 9, 3, 2]])

In [7]:
arr.reshape(2,3)

array([[1, 1, 5],
       [9, 3, 2]])

In [8]:
np.reshape(arr,(1,6))

array([[1, 1, 5, 9, 3, 2]])

In [9]:
arr

array([[1, 1],
       [5, 9],
       [3, 2]])

In [10]:
np.reshape(arr,(2,3),'C')

array([[1, 1, 5],
       [9, 3, 2]])

In [11]:
np.reshape(arr,(2,3),'F')

array([[1, 3, 9],
       [5, 1, 2]])

In [12]:
np.reshape(arr,(2,3),'A')

array([[1, 1, 5],
       [9, 3, 2]])

In [13]:
np.reshape(arr,(2,9),'C')

ValueError: cannot reshape array of size 6 into shape (2,9)