In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])

In [3]:
arr.dtype

dtype('int32')

In [4]:
arr = np.array([1, 2, 3, 4], dtype = 'float64')
arr.dtype

dtype('float64')

In [5]:
arr

array([1., 2., 3., 4.])

In [6]:
arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [7]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [8]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [9]:
arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

| Numpy type      | C type | Description     |
| :----:         |    :----:   |          :----:  |
| numpy.bool_      | bool       | Boolean (True or False) stored as a byte   |
| numpy.byte   | signed char        | Platform-defined |
|numpy.ubyte| unsigned char| Platform-defined|
|numpy.short | short| Platform-defined |
|numpy.ushort |unsigned short |Platform-defined|
|numpy.intc|int|Platform-defined|
|numpy.uintc|unsigned int|Platform-defined|
|numpy.int_|long|Platform-defined|
|numpy.uint|unsigned long|Platform-defined|
|numpy.longlong|long long|Platform-defined|
|numpy.ulonglong|unsigned long long|Platform-defined|
|numpy.half / numpy.float16||Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
|numpy.single|float|Platform-defined single precision float: typically sign bit, 8 bits exponent, 23 bits mantissa|
|numpy.double|double|Platform-defined double precision float: typically sign bit, 11 bits exponent, 52 bits mantissa.|
|numpy.longdouble|long double|Platform-defined extended-precision float|
|numpy.csingle|float complex|Complex number, represented by two single-precision floats (real and imaginary components)|
|numpy.cdouble|double complex|Complex number, represented by two double-precision floats (real and imaginary components).|
|numpy.clongdouble|long double complex|Complex number, represented by two extended-precision floats (real and imaginary components).|